import React from 'react';
import { motion } from 'motion/react';

export interface Transformation {
  id: string | number;
  clientName: string;
  beforeImage: string;
  afterImage: string;
  quote?: string;
  duration?: string;
}

export interface TransformationsGalleryProps {
  title?: string;
  subtitle?: string;
  transformations: Transformation[];
}

export default function TransformationsGallery({
  title = "Real People. Real Results.",
  subtitle = "Don't just take our word for it. See the transformations generated by the Alpha System.",
  transformations
}: TransformationsGalleryProps) {
  
  if (!transformations || transformations.length === 0) return null;

  return (
    <section className="py-24 bg-surface-container-lowest border-b border-white/5">
      <div className="max-w-7xl mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-black font-headline mb-4">{title}</h2>
          <p className="text-on-surface-variant max-w-xl mx-auto">{subtitle}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {transformations.map((item, index) => (
            <motion.div 
              key={item.id}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              className="glass-card p-4 rounded-3xl flex flex-col group relative overflow-hidden"
            >
              {/* Image Grid Before & After */}
              <div className="grid grid-cols-2 gap-2 mb-6 h-64 rounded-2xl overflow-hidden relative">
                <div className="relative h-full">
                  <img src={item.beforeImage} alt={`${item.clientName} Before`} className="w-full h-full object-cover" />
                  <div className="absolute top-2 left-2 bg-black/60 backdrop-blur-md px-2 py-1 rounded text-[10px] uppercase font-bold tracking-wider">Before</div>
                </div>
                <div className="relative h-full">
                  <img src={item.afterImage} alt={`${item.clientName} After`} className="w-full h-full object-cover" />
                  <div className="absolute top-2 right-2 bg-primary/90 text-on-primary px-2 py-1 rounded text-[10px] uppercase font-bold tracking-wider">After</div>
                </div>
              </div>

              {/* Details */}
              <div className="px-2 flex-grow flex flex-col">
                <div className="flex justify-between items-center mb-3">
                  <h3 className="text-xl font-bold font-headline">{item.clientName}</h3>
                  {item.duration && (
                    <span className="text-xs font-semibold px-2 py-1 bg-white/10 rounded-full text-on-surface-variant">
                      {item.duration}
                    </span>
                  )}
                </div>
                
                {item.quote && (
                  <p className="text-sm text-on-surface-variant italic border-l-2 border-primary/50 pl-3 py-1 mb-4">
                    "{item.quote}"
                  </p>
                )}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
